# Generated by Django 4.0.3 on 2022-04-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d', verbose_name='Картинка'),
        ),
    ]
