# Generated by Django 4.0.3 on 2022-04-10 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_picture_picture_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='image',
            new_name='picture',
        ),
    ]
